# config.yaml

parameters:
  - id: config1
    epochs: 5
    batch_size: 64
  - id: config2
    epochs: 10
    batch_size: 128
  - id: config3
    epochs: 15
    batch_size: 256
  # Add more configurations as needed
