# config.yaml

local: true # Set to 'false' to submit jobs to HPC using sbatch

# ignored when local: true
sbatch_defaults:
  time: "01:00:00"
  mem: "4G"
  cpus_per_task: 4
  partition: "default"
  output: "sbatch.out"
  error: "sbatch.err"

parameters:
  - id: config1
    epochs: 5
    batch_size: 64
  - id: config2
    epochs: 10
    batch_size: 128
  - id: config3
    epochs: 7
    batch_size: 256
